### ISSUE TITLE
Link broken for load_pheonix_stars()

### ISSUE THREAD

**Issue by kelceydavis33** [gbrammer/eazy-photoz#12]
I  am attempting to access your templates but when I follow the link in your documentation here:

https://eazy-py.readthedocs.io/en/latest/api/eazy.templates.load_phoenix_stars.html#eazy.templates.load_phoenix_stars

Which leads me to this link:

https://s3.amazonaws.com/grizli/CONF/bt-settl_t400-7000_g4.5.fits

It seems to be broken. The file cannot be accessed in an internet browser or through a wget command in the command line.

**Comment by gbrammer** [comment]
This should be filed on [eazy-py](https://github.com/gbrammer/eazy-py/issues).  But note also that the URL was fixed with https://github.com/gbrammer/eazy-py/commit/0e0b6e76ac72d6a673fb8c8491d1fc5a31ee7dbd: see https://github.com/gbrammer/eazy-py/blob/master/eazy/templates.py#L1335.
