### ISSUE TITLE
nfilt reporting for rest frame color calculations

### ISSUE THREAD

**Issue by jmann02** [gbrammer/eazy-photoz#7]
When fitting for rest frame colors, the *.rf output file does not accurately reflect the number of filters used during the fitting process.  Null data from the input catalog are not used during the fit, but are included as if they were in the "nfilt" output variable.  For example, if 7 filter columns are given and 3 have no data, the eazy program will ignore the 3 null columns during the fit, but report 7 filters were used during the fit.  This issue was verified to be a problem only with reporting the "nfilt" by running the same input data with and without the null columns.  The only difference in output was the number of filters fit.  This is only an issue in the *.rf output file, the *.zout accurately reports that only 4 filters were used.

**Comment by gbrammer** [comment]
This should be fixed now! (see https://github.com/gbrammer/eazy-photoz/commit/164dcac6b832421c34607ee28983d2d76586bbd5)
